### ISSUE TITLE
Using node_modules installed packaged plugin

### ISSUE THREAD

**Issue by piercus** [Accenture/serverless-ephemeral#12]
I think tensorflow packager should be published on npm separately like :
**package.json**
```json
"devDependencies" : {
  "ephemeral-packager-tensorflow": "^0.2.1"
}
```
**serverless.yml**
```yml
custom:
  ephemeral:
    libraries:
      - packager:
          name: ephemeral-packager-tensorflow
          version: 1.4.0
```

If we add this possibility, i owuld be happy to create 2 more packager for node-canvas and node-opencv (see my dockerFiles in https://hub.docker.com/r/piercus/lambda-canvas/ and https://hub.docker.com/r/piercus/lambda-opencv/ with the excat same purpose)

Please share your point of view about this.
